### ISSUE TITLE
Sorry, an error prevented Inkcut from starting

### ISSUE THREAD

**Issue by tim23x** [inkcut/inkcut#324] opened 2022-01-19 14:16 UTC
[inkcut.txt](https://github.com/inkcut/inkcut/files/7897758/inkcut.txt)

Trying to run Inkcut from a fresh install of Python after installing Pyqt5 and Inkcut (log file attached).

Thanks!

**Comment by frmdstryr** [comment] 2022-01-25 21:33
Duplicate of https://github.com/inkcut/inkcut/issues/320 Try using python 3.9 until this is fixed

**Closed by frmdstryr** 2022-01-25 21:33 UTC
Labels: duplicate
