### ISSUE TITLE
Mac Inkcut has no "device setup" 

### ISSUE THREAD

**Issue by artfulnomad** [inkcut/inkcut#205] opened 2020-01-01 17:20 UTC
First of all I'm a rookie diving into this world, so my apologies if this seems trivial but I'll be grateful for any help! I've loaded Inkscape and Inkcut to use my Roland GX-24 cutter. Unfortunately I'm unable to view or open the "device setup" in Inkcut or view any mention of it on the application. Even when I go to print there's no option to open it.

On a separate note the plugin/extension is not sending paths to Inkcut from Inkscape. 

Currently using Mac Mojave 10.14.6

Over all would just like to use Inkscape and sent to the GX24 from my Mac. If there's a better way I'm all ears.

Thx!!

<img width="964" alt="Screen Shot 2020-01-01 at 9 06 16 AM" src="https://user-images.githubusercontent.com/59417054/71643993-0af7da80-2c76-11ea-9548-065222c39412.png">

**Comment by DeeEmm** [comment] 2020-01-24 01:15
Can confirm. Same issue here.

However you can still access the dialog by using the keyboard shortcut opt+cmd+p

**Comment by artfulnomad** [comment] 2020-01-24 02:32
Unfortunately I’m not able to for some reason. Decide to go to Linux and it works great here.

**Comment by frmdstryr** [comment] 2020-03-05 12:57
Duplicate of #181

**Closed by frmdstryr** 2020-03-05 12:57 UTC

**Comment by DeeEmm** [comment] 2020-08-15 10:20
You have closed this as being a duplicate of #181 but yet you have closed #181 as being an issue of this issue.

So I have opened #267  as this issue has not been fixed and is still present.
