### ISSUE TITLE
NotImplementedError ZMQstream

### ISSUE THREAD

**Issue by jokerper** [inkcut/inkcut#242] opened 2020-04-28 12:49 UTC
Hi

I keep having this issue:

'<pre>self._event_puller = ZMQStream(pipe_in, self.io_loop)
  File "c:\users\joker\appdata\local\programs\python\python38-32\lib\site-packages\zmq\eventloop\zmqstream.py", line 127, in __init__
    self._init_io_state()
  File "c:\users\joker\appdata\local\programs\python\python38-32\lib\site-packages\zmq\eventloop\zmqstream.py", line 546, in _init_io_state
    self.io_loop.add_handler(self.socket, self._handle_events, self.io_loop.READ)
  File "c:\users\joker\appdata\local\programs\python\python38-32\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Users\joker\AppData\Local\Programs\Python\Python38-32\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError</pre>'

`<pre>from .graphicsItems.VTickGroup import *
  File "c:\users\joker\appdata\local\programs\python\python38-32\lib\site-packages\pyqtgraph\graphicsItems\VTickGroup.py", line 7, in <module>
    from .. import functions as fn
  File "c:\users\joker\appdata\local\programs\python\python38-32\lib\site-packages\pyqtgraph\functions.py", line 17, in <module>
    from . import debug
  File "c:\users\joker\appdata\local\programs\python\python38-32\lib\site-packages\pyqtgraph\debug.py", line 11, in <module>
    from . import ptime
  File "c:\users\joker\appdata\local\programs\python\python38-32\lib\site-packages\pyqtgraph\ptime.py", line 24, in <module>
    cstart = systime.clock()  ### Required to start the clock in windows
AttributeError: module 'time' has no attribute 'clock'</pre>`

**THE LOG **FILE:**
[inkcut.txt](https://github.com/inkcut/inkcut/files/4545734/inkcut.txt)

I have win10 with python 3.8.2 fresh installed...

I have tried to update/upgrade, what's missing!!!

/jokerper

**Comment by aaujon** [comment] 2020-04-29 14:25
Hi, the problem is the same in #239, this will be fixed by a new version of pyqtgraph.

**Closed** 2020-05-07 17:56 UTC
Labels: duplicate
