### ISSUE TITLE
Inkcut does not start on Ubuntu 19, gives error

### ISSUE THREAD

**Issue by breakbeats573** [inkcut/inkcut#232] opened 2020-02-27 17:37 UTC
kernel_client.start_channels()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/qtconsole/kernel_mixins.py", line 47, in start_channels
    super(QtKernelClientMixin, self).start_channels(*args, **kw)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/ipykernel/inprocess/client.py", line 64, in start_channels
    super(InProcessKernelClient, self).start_channels()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jupyter_client/client.py", line 118, in start_channels
    self.control_channel.start()
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jupyter_client/client.py", line 200, in control_channel
    socket, self.session, self.ioloop
TypeError: ChannelABC() takes no arguments

**Comment by frmdstryr** [comment] 2020-02-27 17:56
Run `pip3 install jupyter-client==5.3.4`.

Duplicate of  #231

**Closed by frmdstryr** 2020-02-27 17:56 UTC
